// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF8AIE02DQaOAJ_3GjSzZAYBBrG5Pl9iM',
    appId: '1:862612307663:web:3429252b618f3bc16801ba',
    messagingSenderId: '862612307663',
    projectId: 'sample-cb5b8',
    authDomain: 'sample-cb5b8.firebaseapp.com',
    storageBucket: 'sample-cb5b8.firebasestorage.app',
    measurementId: 'G-3BTH118EE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOl5xMvLHYNepp3CnwO54wkc9qx4BruR8',
    appId: '1:862612307663:android:e8c108c9cc64e5b66801ba',
    messagingSenderId: '862612307663',
    projectId: 'sample-cb5b8',
    storageBucket: 'sample-cb5b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJzmp26fmVGhEt7L5AKx6HWrkwcB5njQc',
    appId: '1:862612307663:ios:3d09e729573941986801ba',
    messagingSenderId: '862612307663',
    projectId: 'sample-cb5b8',
    storageBucket: 'sample-cb5b8.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJzmp26fmVGhEt7L5AKx6HWrkwcB5njQc',
    appId: '1:862612307663:ios:3d09e729573941986801ba',
    messagingSenderId: '862612307663',
    projectId: 'sample-cb5b8',
    storageBucket: 'sample-cb5b8.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF8AIE02DQaOAJ_3GjSzZAYBBrG5Pl9iM',
    appId: '1:862612307663:web:e3de606bf031616d6801ba',
    messagingSenderId: '862612307663',
    projectId: 'sample-cb5b8',
    authDomain: 'sample-cb5b8.firebaseapp.com',
    storageBucket: 'sample-cb5b8.firebasestorage.app',
    measurementId: 'G-Y83PF2K6CW',
  );
}
